name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [debian, alpine, jdk11, jdk17]
    steps:
      - uses: actions/checkout@v2

      - name: build ${{ matrix.dist }}
        run: make build-${{ matrix.dist }}

  publish-tag:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: publish
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |-
          export GIT_TAG="$(echo ${{ github.event.ref }} | sed 's|refs/tags/||g')"
          make publish

  publish-latest:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: publish
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: make publish


